# Generated by Django 3.0.7 on 2020-07-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0008_auto_20200704_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docrequestlist',
            name='date_podpis',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='date_zagolovok',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='num_podpis',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='num_test',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='num_zagolovok',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='podpis',
            field=models.FileField(blank=True, max_length=30, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='test',
            field=models.FileField(blank=True, max_length=30, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='zagolovok',
            field=models.FileField(blank=True, max_length=30, null=True, upload_to=''),
        ),
    ]
