# Generated by Django 3.0.7 on 2020-07-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0010_docrequestlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docrequestlist',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='zagolovok',
            field=models.FileField(blank=True, null=True, upload_to='zagolovok/'),
        ),
    ]
