# Generated by Django 3.0.7 on 2020-07-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0012_auto_20200704_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docrequestlist',
            name='zagolovok',
            field=models.FileField(blank=True, null=True, upload_to='zagolovoks/'),
        ),
    ]
