# Generated by Django 3.0.7 on 2020-07-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0013_auto_20200704_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docrequestlist',
            name='podpis',
            field=models.FileField(blank=True, max_length=30, null=True, upload_to='podpis/'),
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='zagolovok',
            field=models.FileField(blank=True, null=True, upload_to='zagolovok/'),
        ),
    ]
