# Generated by Django 3.0.7 on 2020-07-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0014_auto_20200705_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docrequestlist',
            name='date_podpis',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='date_test',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='date_zagolovok',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='num_podpis',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='num_test',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='num_zagolovok',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='podpis',
            field=models.FileField(default=2, max_length=30, upload_to='podpis/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='test',
            field=models.FileField(max_length=30, upload_to=''),
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='zagolovok',
            field=models.FileField(blank=True, upload_to='zagolovok/'),
        ),
    ]
