# Generated by Django 3.0.7 on 2020-07-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0016_auto_20200706_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocRequestList',
            new_name='DocRequestListMki',
        ),
    ]
