# Generated by Django 3.0.7 on 2020-07-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0017_auto_20200715_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docrequestlistmki',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='accept_research',
            field=models.FileField(blank=True, null=True, upload_to='accept_research/'),
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='accept_research_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='accept_research_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='advertising',
            field=models.FileField(blank=True, null=True, upload_to='advertising/'),
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='another_doc',
            field=models.FileField(blank=True, null=True, upload_to='another_doc/'),
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='another_doc_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='another_doc_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='cast_researcher',
            field=models.FileField(blank=True, null=True, upload_to='form_inf/'),
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='cast_researcher_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='cast_researcher_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='form_inf',
            field=models.FileField(blank=True, null=True, upload_to='form_inf/'),
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='form_inf_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='form_inf_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='list_members',
            field=models.FileField(blank=True, null=True, upload_to='list_members/'),
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='main_researcher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='name_another_doc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='protocol_research',
            field=models.FileField(blank=True, null=True, upload_to='protocol_research/'),
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='protocol_research_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='protocol_research_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='ver_bio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docrequestlistmki',
            name='write_objects',
            field=models.FileField(blank=True, null=True, upload_to='write_objects/'),
        ),
    ]
