# Generated by Django 3.0.7 on 2020-07-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0019_remove_docrequestlistmki_zagolovok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docrequestlistmki',
            name='date_zagolovok',
        ),
        migrations.RemoveField(
            model_name='docrequestlistmki',
            name='num_zagolovok',
        ),
    ]
