# Generated by Django 3.0.7 on 2020-07-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0021_auto_20200715_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocRequestListNki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('owner', models.CharField(blank=True, max_length=20)),
                ('owner_fio', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('main_researcher', models.CharField(blank=True, max_length=50, null=True)),
                ('list_members', models.FileField(blank=True, null=True, upload_to='list_members/')),
                ('ver_bio', models.CharField(blank=True, max_length=50, null=True)),
                ('accept_research', models.FileField(blank=True, null=True, upload_to='accept_research/')),
                ('accept_research_version', models.CharField(blank=True, max_length=50, null=True)),
                ('accept_research_date', models.CharField(blank=True, max_length=50, null=True)),
                ('protocol_research', models.FileField(blank=True, null=True, upload_to='protocol_research/')),
                ('protocol_research_version', models.CharField(blank=True, max_length=50, null=True)),
                ('protocol_research_date', models.CharField(blank=True, max_length=50, null=True)),
                ('form_inf', models.FileField(blank=True, null=True, upload_to='form_inf/')),
                ('form_inf_version', models.CharField(blank=True, max_length=50, null=True)),
                ('form_inf_date', models.CharField(blank=True, max_length=50, null=True)),
                ('cast_researcher', models.FileField(blank=True, null=True, upload_to='form_inf/')),
                ('cast_researcher_version', models.CharField(blank=True, max_length=50, null=True)),
                ('cast_researcher_date', models.CharField(blank=True, max_length=50, null=True)),
                ('contract', models.FileField(blank=True, null=True, upload_to='contract/')),
                ('contract_date', models.CharField(blank=True, max_length=50, null=True)),
                ('advertising', models.FileField(blank=True, null=True, upload_to='advertising/')),
                ('write_objects', models.FileField(blank=True, null=True, upload_to='write_objects/')),
                ('name_another_doc', models.CharField(blank=True, max_length=50, null=True)),
                ('another_doc', models.FileField(blank=True, null=True, upload_to='another_doc/')),
                ('another_doc_version', models.CharField(blank=True, max_length=50, null=True)),
                ('another_doc_date', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='docrequestlistmki',
            name='date_podpis',
        ),
        migrations.RemoveField(
            model_name='docrequestlistmki',
            name='date_test',
        ),
        migrations.RemoveField(
            model_name='docrequestlistmki',
            name='num_podpis',
        ),
        migrations.RemoveField(
            model_name='docrequestlistmki',
            name='num_test',
        ),
        migrations.RemoveField(
            model_name='docrequestlistmki',
            name='podpis',
        ),
        migrations.RemoveField(
            model_name='docrequestlistmki',
            name='test',
        ),
    ]
