# Generated by Django 3.0.7 on 2020-07-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0022_auto_20200718_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docrequestlistmki',
            name='accept_research',
            field=models.FileField(upload_to='accept_research/'),
        ),
        migrations.AlterField(
            model_name='docrequestlistmki',
            name='accept_research_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docrequestlistmki',
            name='accept_research_version',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docrequestlistmki',
            name='cast_researcher',
            field=models.FileField(upload_to='form_inf/'),
        ),
        migrations.AlterField(
            model_name='docrequestlistmki',
            name='cast_researcher_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docrequestlistmki',
            name='cast_researcher_version',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docrequestlistmki',
            name='contract',
            field=models.FileField(upload_to='contract/'),
        ),
        migrations.AlterField(
            model_name='docrequestlistmki',
            name='contract_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docrequestlistmki',
            name='form_inf',
            field=models.FileField(upload_to='form_inf/'),
        ),
        migrations.AlterField(
            model_name='docrequestlistmki',
            name='form_inf_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docrequestlistmki',
            name='form_inf_version',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docrequestlistmki',
            name='list_members',
            field=models.FileField(upload_to='list_members/'),
        ),
        migrations.AlterField(
            model_name='docrequestlistmki',
            name='main_researcher',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docrequestlistmki',
            name='owner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='docrequestlistmki',
            name='owner_fio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='docrequestlistmki',
            name='protocol_research',
            field=models.FileField(upload_to='protocol_research/'),
        ),
        migrations.AlterField(
            model_name='docrequestlistmki',
            name='protocol_research_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docrequestlistmki',
            name='protocol_research_version',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docrequestlistmki',
            name='ver_bio',
            field=models.CharField(max_length=50),
        ),
    ]
