# Generated by Django 3.0.7 on 2020-07-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0023_auto_20200718_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docrequestlistmki',
            name='main_researcher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
