# Generated by Django 3.0.7 on 2020-07-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0024_auto_20200718_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='docrequestlistmki',
            name='date_create',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
