# Generated by Django 3.0.7 on 2020-07-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0025_docrequestlistmki_date_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docrequestlistmki',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
