# Generated by Django 3.0.7 on 2020-08-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0026_auto_20200723_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='listRequestResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=12)),
                ('date_created', models.CharField(max_length=30)),
            ],
        ),
    ]
