# Generated by Django 3.0.6 on 2020-08-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0027_listrequestresearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='docrequestlistmki',
            name='secretar_accept',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
