# Generated by Django 3.0.7 on 2020-06-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listForRegistration', '0004_registeredusers_usernames'),
    ]

