# Generated by Django 3.0.7 on 2020-06-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listForRegistration', '0005_remove_registeredusers_usernames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredusers',
            name='usernames',
        ),
    ]
