# Generated by Django 3.0.7 on 2020-06-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listForRegistration', '0008_auto_20200627_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredusers',
            name='username_field',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
