# Generated by Django 3.0.7 on 2020-06-29 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listForRegistration', '0009_registeredusers_username_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=30, verbose_name='Наименование роли')),
            ],
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='listForRegistration.Role'),
        ),
    ]
