# Generated by Django 3.0.7 on 2020-07-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listForRegistration', '0014_auto_20200704_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredusers',
            name='dolzhnost',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='num',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='place_work',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
