# Generated by Django 3.0.7 on 2020-07-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listForRegistration', '0015_auto_20200705_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredusers',
            name='dateb',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='num',
            field=models.CharField(max_length=12),
        ),
    ]
