# Generated by Django 3.0.7 on 2020-07-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listForRegistration', '0016_auto_20200713_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredusers',
            name='auth_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
