# Generated by Django 3.0.7 on 2020-07-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0002_docrequestlist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='docrequestlist',
            name='owner_fio',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='owner',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
