# Generated by Django 3.0.7 on 2020-07-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0003_auto_20200702_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='docrequestlist',
            name='date_podpis',
            field=models.CharField(db_index=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docrequestlist',
            name='date_test',
            field=models.CharField(db_index=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docrequestlist',
            name='date_zagolovok',
            field=models.CharField(db_index=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docrequestlist',
            name='num_podpis',
            field=models.CharField(db_index=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docrequestlist',
            name='num_test',
            field=models.CharField(db_index=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docrequestlist',
            name='num_zagolovok',
            field=models.CharField(db_index=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docrequestlist',
            name='podpis',
            field=models.FileField(db_index=True, default='', max_length=30, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docrequestlist',
            name='test',
            field=models.FileField(db_index=True, default='', max_length=30, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docrequestlist',
            name='zagolovok',
            field=models.FileField(db_index=True, default='', max_length=30, upload_to=''),
            preserve_default=False,
        ),
    ]
