# Generated by Django 3.0.7 on 2020-07-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0004_auto_20200704_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docrequestlist',
            name='date_podpis',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='date_test',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='date_zagolovok',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='num_podpis',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='num_test',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='num_zagolovok',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='podpis',
            field=models.FileField(max_length=30, upload_to=''),
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='test',
            field=models.FileField(max_length=30, upload_to=''),
        ),
        migrations.AlterField(
            model_name='docrequestlist',
            name='zagolovok',
            field=models.FileField(max_length=30, upload_to='', verbose_name='t'),
        ),
    ]
