# Generated by Django 3.0.7 on 2020-07-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createRequest', '0007_auto_20200704_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docrequestlist',
            name='date_test',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
