# Generated by Django 3.0.7 on 2020-06-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listregisterrequest',
            name='dateb',
            field=models.CharField(max_length=12),
        ),
    ]
