# Generated by Django 3.0.7 on 2020-06-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200625_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='listregisterrequest',
            name='is_superuser',
            field=models.CharField(default='1', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listregisterrequest',
            name='last_login',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listregisterrequest',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listregisterrequest',
            name='role',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
