# Generated by Django 3.0.7 on 2020-06-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_remove_listregisterrequest_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listregisterrequest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='listregisterrequest',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='listregisterrequest',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='listregisterrequest',
            name='password',
        ),
    ]
