# Generated by Django 3.0.7 on 2020-07-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20200629_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listregisterrequest',
            old_name='dateb',
            new_name='num',
        ),
    ]
