# Generated by Django 3.0.7 on 2020-06-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registeredUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('fio', models.CharField(max_length=30)),
                ('dateb', models.CharField(max_length=12)),
            ],
        ),
    ]
