# Generated by Django 3.0.7 on 2020-07-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listForRegistration', '0011_auto_20200629_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredusers',
            name='dolzhnost',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='num',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='place_work',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
