# Generated by Django 3.0.7 on 2020-07-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listForRegistration', '0013_auto_20200703_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredusers',
            name='dolzhnost',
        ),
        migrations.RemoveField(
            model_name='registeredusers',
            name='num',
        ),
        migrations.RemoveField(
            model_name='registeredusers',
            name='place_work',
        ),
    ]
