# Generated by Django 3.0.6 on 2020-10-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listMeetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_meetings', models.CharField(max_length=200)),
                ('users_invited', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
    ]
