# Generated by Django 3.0.6 on 2020-10-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmeetings',
            name='accepted_meetings_description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listmeetings',
            name='accepted_meetings',
            field=models.CharField(max_length=100),
        ),
    ]
