# Generated by Django 3.0.7 on 2020-06-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listRegisterRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('fio', models.CharField(max_length=30)),
                ('dateb', models.DateField()),
            ],
        ),
    ]
